### ISSUE TITLE
Would be nice if guard villagers can shoot guns in the "old gun mod"

### ISSUE THREAD

**Issue by minicuuuuubs** [grilled-salmon/oldguns#36]
When a guard villager uses a gun from the old gun mod the game will crash and then the save will not load.
When a villager tries to fire a gun from the old guns mod it will crash and corrupt the save file.

I'd like guard villagers being compatible with old guns

**Comment by zach2039** [comment]
Fixed in both [v3.6.3-38](https://github.com/zach2039/oldguns/releases/tag/v3.6.3-38) and [v3.7.1-39](https://github.com/zach2039/oldguns/releases/tag/v3.7.1-39) releases, though the projectile spawned when fired is just an arrow. Will need some help from Guard Villagers' author on how best to tie in proper functionality.
